// Sample Work Order records for TITANIUM COATING SERVICES (matching Coating Rework Sheet layout schema)
const defaultWorkOrders = [
  {
    id: "3280",
    date: "2026-05-20",
    poNumber: "PO-2026-0518",
    inspector: "RM",
    customer: "HydraForce Systems",
    partCoating: "AL-4022-T / ALPHA-T-TIN",
    parts: [
      { partNoDescription: "AL-4022-T End Cap A", qtyRejected: 12, reasonForRework: "Coating peeling on thread chamfer", qtyReworkCompleted: 12, notes: "Stripped and recoated. Passed inspection." },
      { partNoDescription: "AL-4022-T End Cap B", qtyRejected: 6, reasonForRework: "Pinholes in coating layer", qtyReworkCompleted: 6, notes: "Stripped and recoated. Passed inspection." },
      { partNoDescription: "", qtyRejected: "", reasonForRework: "", qtyReworkCompleted: "", notes: "" },
      { partNoDescription: "", qtyRejected: "", reasonForRework: "", qtyReworkCompleted: "", notes: "" },
      { partNoDescription: "", qtyRejected: "", reasonForRework: "", qtyReworkCompleted: "", notes: "" },
      { partNoDescription: "", qtyRejected: "", reasonForRework: "", qtyReworkCompleted: "", notes: "" },
      { partNoDescription: "", qtyRejected: "", reasonForRework: "", qtyReworkCompleted: "", notes: "" },
      { partNoDescription: "", qtyRejected: "", reasonForRework: "", qtyReworkCompleted: "", notes: "" }
    ],
    processUltrasonic: true,
    processStripping: true,
    processSandBlasting: false,
    processPolishing: false,
    processCoating: true,
    processOther: false,
    processOtherText: "",
    reworkPerformedBy: "Mark R.",
    reworkDate: "2026-05-22",
    reworkQcResult: "Passed",
    reworkQcInitial: "QC1",
    reworkQcDate: "2026-05-24",
    createdTime: "2026-05-20T09:15:00Z",
    lastModifiedTime: "2026-05-24T15:30:00Z"
  },
  {
    id: "3281",
    date: "2026-05-25",
    poNumber: "PO-77402-DW",
    inspector: "ER",
    customer: "Deepwater Energy Corp",
    partCoating: "SS-7711-V / ALPHA-TC-TICN",
    parts: [
      { partNoDescription: "SS-7711-V Valve Stem Alpha", qtyRejected: 4, reasonForRework: "Adhesion failure at base", qtyReworkCompleted: 2, notes: "2 parts failed re-adhesion test." },
      { partNoDescription: "SS-7711-V Valve Stem Beta", qtyRejected: 5, reasonForRework: "Excessive roughness on seal face", qtyReworkCompleted: 5, notes: "Polished and recoated. Passed." },
      { partNoDescription: "", qtyRejected: "", reasonForRework: "", qtyReworkCompleted: "", notes: "" },
      { partNoDescription: "", qtyRejected: "", reasonForRework: "", qtyReworkCompleted: "", notes: "" },
      { partNoDescription: "", qtyRejected: "", reasonForRework: "", qtyReworkCompleted: "", notes: "" },
      { partNoDescription: "", qtyRejected: "", reasonForRework: "", qtyReworkCompleted: "", notes: "" },
      { partNoDescription: "", qtyRejected: "", reasonForRework: "", qtyReworkCompleted: "", notes: "" },
      { partNoDescription: "", qtyRejected: "", reasonForRework: "", qtyReworkCompleted: "", notes: "" }
    ],
    processUltrasonic: true,
    processStripping: true,
    processSandBlasting: true,
    processPolishing: true,
    processCoating: true,
    processOther: false,
    processOtherText: "",
    reworkPerformedBy: "Steve J.",
    reworkDate: "2026-05-27",
    reworkQcResult: "Needs Additional Rework",
    reworkQcInitial: "QC2",
    reworkQcDate: "2026-05-28",
    createdTime: "2026-05-25T14:20:00Z",
    lastModifiedTime: "2026-05-28T11:10:00Z"
  },
  {
    id: "3282",
    date: "2026-05-28",
    poNumber: "PO-AJ-5582",
    inspector: "JV",
    customer: "AeroJet Engineering",
    partCoating: "TI-9910-A / ALPHA-AT-ALTIN",
    parts: [
      { partNoDescription: "TI-9910-A Rotor Hub A", qtyRejected: 2, reasonForRework: "Dimensional out-of-spec", qtyReworkCompleted: 0, notes: "Stripping failed to recover core dimensions." },
      { partNoDescription: "", qtyRejected: "", reasonForRework: "", qtyReworkCompleted: "", notes: "" },
      { partNoDescription: "", qtyRejected: "", reasonForRework: "", qtyReworkCompleted: "", notes: "" },
      { partNoDescription: "", qtyRejected: "", reasonForRework: "", qtyReworkCompleted: "", notes: "" },
      { partNoDescription: "", qtyRejected: "", reasonForRework: "", qtyReworkCompleted: "", notes: "" },
      { partNoDescription: "", qtyRejected: "", reasonForRework: "", qtyReworkCompleted: "", notes: "" },
      { partNoDescription: "", qtyRejected: "", reasonForRework: "", qtyReworkCompleted: "", notes: "" },
      { partNoDescription: "", qtyRejected: "", reasonForRework: "", qtyReworkCompleted: "", notes: "" }
    ],
    processUltrasonic: false,
    processStripping: true,
    processSandBlasting: false,
    processPolishing: false,
    processCoating: false,
    processOther: true,
    processOtherText: "Chemical acid etch",
    reworkPerformedBy: "Karl S.",
    reworkDate: "2026-06-01",
    reworkQcResult: "Failed",
    reworkQcInitial: "QC1",
    reworkQcDate: "2026-06-02",
    createdTime: "2026-05-28T08:00:00Z",
    lastModifiedTime: "2026-06-02T17:20:00Z"
  },
  {
    id: "3283",
    date: "2026-06-01",
    poNumber: "PO-998822-AD",
    inspector: "SJ",
    customer: "AeroDynamics Propulsion Inc.",
    partCoating: "AC-8890 / ALPHA-TC-TICN",
    parts: [
      { partNoDescription: "AC-8890 Fan Blade Right", qtyRejected: 8, reasonForRework: "Overspray on blade tips", qtyReworkCompleted: 8, notes: "Stripped and recoated." },
      { partNoDescription: "AC-8890 Fan Blade Left", qtyRejected: 8, reasonForRework: "Overspray on blade tips", qtyReworkCompleted: 8, notes: "Stripped and recoated." },
      { partNoDescription: "", qtyRejected: "", reasonForRework: "", qtyReworkCompleted: "", notes: "" },
      { partNoDescription: "", qtyRejected: "", reasonForRework: "", qtyReworkCompleted: "", notes: "" },
      { partNoDescription: "", qtyRejected: "", reasonForRework: "", qtyReworkCompleted: "", notes: "" },
      { partNoDescription: "", qtyRejected: "", reasonForRework: "", qtyReworkCompleted: "", notes: "" },
      { partNoDescription: "", qtyRejected: "", reasonForRework: "", qtyReworkCompleted: "", notes: "" },
      { partNoDescription: "", qtyRejected: "", reasonForRework: "", qtyReworkCompleted: "", notes: "" }
    ],
    processUltrasonic: true,
    processStripping: true,
    processSandBlasting: true,
    processPolishing: false,
    processCoating: true,
    processOther: false,
    processOtherText: "",
    reworkPerformedBy: "Thomas R.",
    reworkDate: "2026-06-03",
    reworkQcResult: "Passed",
    reworkQcInitial: "QC3",
    reworkQcDate: "2026-06-05",
    createdTime: "2026-06-01T08:30:00Z",
    lastModifiedTime: "2026-06-05T16:45:00Z"
  },
  {
    id: "3284",
    date: "2026-06-04",
    poNumber: "PO-TI-88901",
    inspector: "DK",
    customer: "Titan Infrastructure",
    partCoating: "CS-5044-B / ALPHA-T-TIN",
    parts: [
      { partNoDescription: "CS-5044-B Structural Bracket", qtyRejected: 45, reasonForRework: "Incomplete coating coverage", qtyReworkCompleted: "", notes: "" },
      { partNoDescription: "", qtyRejected: "", reasonForRework: "", qtyReworkCompleted: "", notes: "" },
      { partNoDescription: "", qtyRejected: "", reasonForRework: "", qtyReworkCompleted: "", notes: "" },
      { partNoDescription: "", qtyRejected: "", reasonForRework: "", qtyReworkCompleted: "", notes: "" },
      { partNoDescription: "", qtyRejected: "", reasonForRework: "", qtyReworkCompleted: "", notes: "" },
      { partNoDescription: "", qtyRejected: "", reasonForRework: "", qtyReworkCompleted: "", notes: "" },
      { partNoDescription: "", qtyRejected: "", reasonForRework: "", qtyReworkCompleted: "", notes: "" },
      { partNoDescription: "", qtyRejected: "", reasonForRework: "", qtyReworkCompleted: "", notes: "" }
    ],
    processUltrasonic: false,
    processStripping: false,
    processSandBlasting: false,
    processPolishing: false,
    processCoating: false,
    processOther: false,
    processOtherText: "",
    reworkPerformedBy: "",
    reworkDate: "",
    reworkQcResult: "pending",
    reworkQcInitial: "",
    reworkQcDate: "",
    createdTime: "2026-06-04T10:10:00Z",
    lastModifiedTime: "2026-06-04T10:15:00Z"
  }
];
