// Sample Work Order records for TITANIUM COATING SERVICES, INC., Inc. (matching Mockup layout schema)
const defaultWorkOrders = [
  {
    id: "3280",
    customerName: "HydraForce Systems",
    priority: "Medium",
    partNo: "AL-4022-T",
    poNumber: "PO-2026-0518",
    dueDate: "2026-06-01",
    coating: "ALPHA-T-TIN",
    receivingDate: "2026-05-20",
    instructions: "Rack parts on internal threads to prevent damage. Anodize at 32°F for 45 minutes. Seal in hot nickel acetate bath for 15 minutes. Check bore dimension post-coating.",
    parts: [
      { part: "AL-4022-T End Cap A", quantity: 60 },
      { part: "AL-4022-T End Cap B", quantity: 60 },
      { part: "", quantity: "" },
      { part: "", quantity: "" },
      { part: "", quantity: "" },
      { part: "", quantity: "" },
      { part: "", quantity: "" }
    ],
    receivingInitial: "RM",
    shippingInitial: "JS",
    sandblast: "FINE",
    footerReceivingDate: "2026-05-20",
    footerReceivingInitial: "RM",
    footerQcInitial: "QC1",
    footerShippingDate: "2026-05-24",
    footerShippingInitial: "JS",
    forTcs: "Batch meets MIL specs. Processed under control line 2.",
    createdTime: "2026-05-20T09:15:00Z",
    lastModifiedTime: "2026-05-24T15:30:00Z"
  },
  {
    id: "3281",
    customerName: "Deepwater Energy Corp",
    priority: "High",
    partNo: "SS-7711-V",
    poNumber: "PO-77402-DW",
    dueDate: "2026-06-08",
    coating: "ALPHA-TC-TICN",
    receivingDate: "2026-05-25",
    instructions: "Bake at 375°F for 4 hours within 3 hours of plating. Inspect critical seal surfaces under 10x magnification. Ensure no micro-cracking.",
    parts: [
      { part: "SS-7711-V Valve Stem Alpha", quantity: 6 },
      { part: "SS-7711-V Valve Stem Beta", quantity: 6 },
      { part: "", quantity: "" },
      { part: "", quantity: "" },
      { part: "", quantity: "" },
      { part: "", quantity: "" },
      { part: "", quantity: "" }
    ],
    receivingInitial: "ER",
    shippingInitial: "DB",
    sandblast: "ROUGH",
    footerReceivingDate: "2026-05-25",
    footerReceivingInitial: "ER",
    footerQcInitial: "QC2",
    footerShippingDate: "2026-05-28",
    footerShippingInitial: "DB",
    forTcs: "High Phosphorus ENP target achieved.",
    createdTime: "2026-05-25T14:20:00Z",
    lastModifiedTime: "2026-05-28T11:10:00Z"
  },
  {
    id: "3282",
    customerName: "AeroJet Engineering",
    priority: "High",
    partNo: "TI-9910-A",
    poNumber: "PO-AJ-5582",
    dueDate: "2026-06-15",
    coating: "ALPHA-AT-ALTIN",
    receivingDate: "2026-05-28",
    instructions: "Preheat substrate to 300°F. Apply TBC top coat to 12.0 mils thickness. Perform non-destructive thermal cycling inspection. Check adhesion strength.",
    parts: [
      { part: "TI-9910-A Rotor Hub A", quantity: 2 },
      { part: "TI-9910-A Rotor Hub B", quantity: 2 },
      { part: "", quantity: "" },
      { part: "", quantity: "" },
      { part: "", quantity: "" },
      { part: "", quantity: "" },
      { part: "", quantity: "" }
    ],
    receivingInitial: "JV",
    shippingInitial: "KS",
    sandblast: "FINE",
    footerReceivingDate: "2026-05-28",
    footerReceivingInitial: "JV",
    footerQcInitial: "QC1",
    footerShippingDate: "2026-06-02",
    footerShippingInitial: "KS",
    forTcs: "Thermal barrier verified. Adhesion test passed.",
    createdTime: "2026-05-28T08:00:00Z",
    lastModifiedTime: "2026-06-02T17:20:00Z"
  },
  {
    id: "3283",
    customerName: "AeroDynamics Propulsion Inc.",
    priority: "High",
    partNo: "AC-8890",
    poNumber: "PO-998822-AD",
    dueDate: "2026-06-12",
    coating: "ALPHA-TC-TICN",
    receivingDate: "2026-06-01",
    instructions: "Apply double pass coating. Pre-bake parts at 150°F for 30 mins, cure at 400°F for 1 hour. Verify thickness in 5 random areas per batch. Target: >4H Pencil Hardness.",
    parts: [
      { part: "AC-8890 Fan Blade Right", quantity: 24 },
      { part: "AC-8890 Fan Blade Left", quantity: 24 },
      { part: "", quantity: "" },
      { part: "", quantity: "" },
      { part: "", quantity: "" },
      { part: "", quantity: "" },
      { part: "", quantity: "" }
    ],
    receivingInitial: "SJ",
    shippingInitial: "TR",
    sandblast: "FINE",
    footerReceivingDate: "2026-06-01",
    footerReceivingInitial: "SJ",
    footerQcInitial: "QC3",
    footerShippingDate: "2026-06-05",
    footerShippingInitial: "TR",
    forTcs: "Uniform cure achieved. Hardness target met.",
    createdTime: "2026-06-01T08:30:00Z",
    lastModifiedTime: "2026-06-05T16:45:00Z"
  },
  {
    id: "3284",
    customerName: "Titan Infrastructure",
    priority: "Low",
    partNo: "CS-5044-B",
    poNumber: "PO-TI-88901",
    dueDate: "2026-06-20",
    coating: "ALPHA-T-TIN",
    receivingDate: "2026-06-04",
    instructions: "Dip-spin coating application. Cure at 600°F for 25 minutes. Ensure no accumulation in bracket holes or recesses. Check thread clearance.",
    parts: [
      { part: "CS-5044-B Structural Bracket", quantity: 500 },
      { part: "", quantity: "" },
      { part: "", quantity: "" },
      { part: "", quantity: "" },
      { part: "", quantity: "" },
      { part: "", quantity: "" },
      { part: "", quantity: "" }
    ],
    receivingInitial: "DK",
    shippingInitial: "",
    sandblast: "NONE",
    footerReceivingDate: "2026-06-04",
    footerReceivingInitial: "DK",
    footerQcInitial: "",
    footerShippingDate: "",
    footerShippingInitial: "",
    forTcs: "Zinc flake dip-spin curing pending validation.",
    createdTime: "2026-06-04T10:10:00Z",
    lastModifiedTime: "2026-06-04T10:15:00Z"
  }
];
